plg = newplugin()
plg.id    = 'WebRelationsTree'
plg.name  = _("Web Relations Tree")
plg.description =  _("Produces web (HTML) interactive relations tree.")
plg.version = '0.1'
plg.gramps_target_version = MODULE_VERSION
plg.status = STABLE
plg.fname = 'webreltree.py'
plg.ptype = REPORT
plg.authors = ["Aleksey Morarash"]
plg.authors_email = ["tuxofil@gmail.com"]
plg.category =  CATEGORY_WEB
plg.reportclass = 'WebRelTreeReport'
plg.optionclass = 'WebRelTreeOptions'
plg.report_modes = [REPORT_MODE_GUI]
plg.require_active = True
